### ISSUE TITLE
Integreatly OperatorSource should be pulled from the cluster

### ISSUE THREAD

**Issue by sedroche** [integr8ly/integreatly-operator#17]
Issue originating from this discussion: https://github.com/integr8ly/integreatly-operator/pull/16#discussion_r292077852

OperatorSource is hardcoded atm. This should ideally be pulled from the cluster as the OperatorSource should already be created as a prerequisite of integreatly installations.
Maybe OperatorSource name can be passed as a param.

**Comment by matskiv** [comment]
Out of date.
@philbrookes can you close this please?
