### ISSUE TITLE
Import/Vendor the Keycloak APIs from the keycloak operator instead of copying them

### ISSUE THREAD

**Issue by sedroche** [integr8ly/integreatly-operator#19]
We are currently copying the API files from the keycloak operator instead of importing/vendoring them.
This is because keycloak operator uses operator sdk version 0.0.7 and integreatly operator uses 0.7.0 which means the apis are incompatible.

We should switch to importing the apis from keycloak operator once the operator sdk has been updated.

**Comment by matskiv** [comment]
Out of date.
@philbrookes can you close this please?
