### ISSUE TITLE
Certificate error in codeready-containers causing a CrashLoopBackoff

### ISSUE THREAD

**Issue by akoserwal** [integr8ly/integreatly-operator#278]
**Error**
```
Caused by: java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: https://keycloak-integreatly-rhsso.apps-crc.testing/auth/realms/openshift/.well-known/openid-configuration
```
**Env**: CRC [CodeReady Containers - OpenShift 4.2](https://github.com/code-ready/crc)

**Description**
Route generated for the keycloak has DNS names: keycloak.rhmi-rhsso.svc or the subject name: keycloak.rhmi-rhsso.svc. Hostname/route name: https://keycloak-rhmi-rhsso.apps-crc.testing/. When code-ready workspace tries to access the keycloak host, it fails because neither the certificate common name (CN in certification Subject) nor any of the alternate names (Subject Alternative Name in the certificate) match with the target hostname. DNS names generated would be in the formate: `<service.name>.<service.namespace>.svc.`

**Comment by grdryn** [comment]
@philbrookes @matskiv any ideas or suggestions for Abhishek?

@akoserwal note that you'll need quite a beefy machine if you plan to get all of integreatly installed on CRC. I'm not sure if anyone has tried it in earnest yet.

**Comment by akoserwal** [comment]
@grdryn: I am using the products flag to try out specific products. Solving this issue requires a valid certificate with matched alt names/dns names. Is there a way to configure it? as this route is generated by the reconciler:`: https://keycloak-rhmi-rhsso.apps-crc.testing/.`

**Comment by matskiv** [comment]
@akoserwal Have you tried setting `spec.selfSignedCerts = true` in your Installation CR?

**Comment by akoserwal** [comment]
yes

**Comment by matskiv** [comment]
@akoserwal FYI: we upgraded to CodeReady 2.0 (https://github.com/integr8ly/integreatly-operator/pull/280), let us know if that solves the problem if you will be trying it out again.

**Comment by akoserwal** [comment]
@matskiv: I would like to test it out. but seems like an issue with sso. stuck at it

**Comment by matskiv** [comment]
@akoserwal are there any errors in integreatly-operator logs, or in a SSO operator pod logs?
If not, I think it would be best to schedule a call to take a look at this together. Feel free to schedule one, my kerberos name is omatskiv.

**Comment by akoserwal** [comment]
Errors: https://pastebin.com/uppwT3Kb

**Comment by matskiv** [comment]
@akoserwal Based on the error, you seem to be using old keycloak operator. We merged new version today, and it has significant changes, so it's not really worth the time to try debug this issue with old version.
Could you please try it again with new version:
- pull master and check that you have this folder: `integreatly-operator/manifests/integreatly-rhsso/rhsso-8.0.1/`
- remove sso namespace from your cluster
- remove Keycloak and KeycloakRealm CRDs from your cluster
And then run the installation again.
