### ISSUE TITLE
Readme is incorrect for 2.x

### ISSUE THREAD

**Issue by pwright** [integr8ly/integreatly-operator#355]
afaik, manifest.yaml does not determine versions in 2.x, possibly replaced by https://github.com/integr8ly/integreatly-operator/blob/master/pkg/apis/integreatly/v1alpha1/installation_types.go

Any plans to update readme?
ping @jasonmadigan

**Comment by matskiv** [comment]
@pwright Which part of the Readme are you referring to?

**Comment by pwright** [comment]
@matskiv oops, I've confused this readme with https://github.com/integr8ly/installation/blob/master/README.adoc
