### ISSUE TITLE
keycloak pod failed readiness probe, going in crashloop

### ISSUE THREAD

**Issue by akoserwal** [integr8ly/integreatly-operator#430]
For Openshift Cluster with (4.2/4.3) with valid TLS certificate (using let's encrypt):

keycloak pod environment variable
`X509_CA_BUNDLE: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
instead 
`/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt`

Because of the incorrect CA certificate, the routes generated are misconfigured and showing the default openshift error page, which is causing the liveness probes to fail & pod is going on a crash loop. It will work for vanilla k8s and local CRC instance

**Comment by sigreen** [comment]
I seem to be experiencing this issue as well with release v2.0.0.  Did we find a workaround?

**Comment by akoserwal** [comment]
work-around branch: https://github.com/akoserwal/integreatly-operator/tree/keycloak-cert-fix

**Comment by philbrookes** [comment]
Would this fix be better PRed against the upstream [keycloak-operator repo](https://github.com/keycloak/keycloak-operator), as the integreatly-operator intends to move to using the upstream operator again, in the near future. As this is really an issue in the keycloak-operator, I feel that this issue would be better opened against their repo also?

**Comment by akoserwal** [comment]
sure, I will open an issue with keycloak operator.

**Comment by philbrookes** [comment]
Great, I will close this issue then.
