### ISSUE TITLE
[Question] Cluster Operator: Does Dedicated-Admin have Operator Administration Permission

### ISSUE THREAD

**Issue by GrooveCS** [integr8ly/integreatly-operator#934]
# Cluster Operator: Dedicated-Admin have Operator Administration Permission

Labels: documentation

```! bash
┌[Parris@com.RedHat]
└[~]> oc login --token=... --server=https://api.cluster-b289.b289.example.opentlc.com:6443
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

Logged into "https://api.cluster-b289.b289.example.opentlc.com:6443" as "dedicated-admin" using the token provided.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * dedicated-admin-fuse
    redhat-rhmi-fuse

Using project "dedicated-admin-fuse".

┌[Parris@com.RedHat]
└[~]> oc version
Client Version: 4.5.0-0.nightly-2020-05-09-204657
Kubernetes Version: v1.16.2
```

### Expected Behavior

1.  Dedicated-Admin - CRUD Operators in their cluster or Project (Namespace)
1. Dedicated-Admin - Create Groups & Roles to Operator permissions
1. Dedicated-Admin - Assign Users to Groups & Roles Cluster Wide
1. Dedicated-Admin - Assign Users to Groups & Roles to specific Project (Namespace)

### Actual Behavior

1. Signed in as Cluster-Admin rights to add operators from Operator Hub
1. Signed into as Dedicated-Admin no rights to add additional operators
1. Signed into as evals no rights to add other operators

**Comment by philbrookes** [comment]
Hello @GrooveCS the dedicated-admin group is considered to be an admin at the customer level, we have a PR open that is trying to document the dedicated-admin role in the integreatly setting, if you'd like to take a look at this, it may provide some clarity: https://github.com/integr8ly/integreatly-operator/pull/928/files
